config/routes.rb
Rails.application.routes.draw do

  get 'transition/show'
  devise_for :companies
  get 'public/index'
  get 'public/private'

  devise_for :users, controllers: { registrations: "registrations"} do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
    resources :posts
    resources :comments
    resources :interests
  end

  root to: "posts#index"

  resources :posts do
    member do
      put "like" => "posts#vote"
    end
    resources :users
    resources :interests
    post 'comments', to: 'comments#create'

  end

  resources :comments do
    resources :users
  end

  resources :users do
    resources :posts
    resources :interests
  end
  resources :interests do
    resources :posts
    resources :users
  end
  resources :relationships, only: [:create, :destroy] do
    resources :users
  end
  get 'users/:id/user_posts' => 'users#user_posts', :as => :users_posts
  get 'users/:id/current_user_posts' => 'users#current_user_posts', :as => :current_user_posts
  get 'interests/:id/post_by_interest' => 'interests#post_by_interest', :as => :posts_by_interest
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_one_attached :avatar
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  belongs_to :interest
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships
 
  validates :email, :uniqueness => true
  validates :username, :uniqueness => true

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def self.search(search)
    if search
      where(["username LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   redirect_to posts_path
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    @user = User.find(params[:id])
  end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include UsersHelper
    before_action :set_user, only: %i[show user_posts]
    before_action :authenticate_user!
    def index
        @users = User.search(params[:search])
        # @users = User.all
    end

    def show; end

    def user_posts
        @posts = @user.posts
    end

    def current_user_posts
        @current_posts = current_user.posts
    end

    def edit
        @user_name = User.find(1)
    end
    
    def following
        @title = "Following"
        @user = User.find(params[:id])
        render 'following'
    end

    def followers
        @title = "Followers"
        @user = User.find(params[:id])
        render 'followers'
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def user_params
        params.require(:user).permit(:email, :username, :avatar, :interest_id)
    end

    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
    html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn red" %>
<% end %>

app/views/users/current_user_posts.html.erb
<%= render partial: "shared/nav" %>

<div class="container center-align w-content">
        <% if current_user.posts.empty? %>
          <%= link_to  "Add a new one", new_post_path, class:"btn teal" %>
          <div class="not-found">
                No posts
          </div>
        <% else %>
          <h4>Manage your posts</h4>
        <% current_user.posts.each do |c_post| %>
        <div class="post">
        <p><%= c_post.content.capitalize %><br></p>
        <%= link_to 'View post', post_path(c_post), class:"btn blue" %>
        <%= link_to 'Edit', edit_post_path(c_post), class:"btn" %>
        <%= link_to 'Delete', c_post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn red" %>
        <%end%>
        <% end %>
     
</div>

app/views/users/followers.html.erb
<%= render partial: "shared/nav" %>

<% if @user.followers.empty? %>
    <div class="container center-align w-content">
     <div class="row not-found">
          No follower yet
     </div>
    </div>
<% else %>
  <div class="container center-align w-content">
  <h4 class="flow-text"><%= @user.username.capitalize%> followers</h4>

 <table class="highlight responsive-table centered">
        <thead>
          <tr>
              
              <th>Username</th>
              
          </tr>
        </thead>

        <tbody>
<% @user.followers.each do |followers| %>
          <tr>
               <td>
                    <%= link_to followers.username.capitalize, relationship_user_path(@user.followers, followers) %>
               </td>
          </tr>
          <% end %>
        </tbody>
  </table>
<% end %>

app/views/users/following.html.erb
<%= render partial: "shared/nav" %>


<% if @user.following.empty? %>
    <div class="container center-align w-content">
     <div class="row not-found">
          No follower yet
     </div>
    </div>
<% else %>
  <div class="container center-align w-content">
  <h4 class="flow-text"><%= @user.username.capitalize%> following</h4>
 <table class="highlight responsive-table centered">
        <thead>
          <tr>
              
          <th>Username</th>
              
          </tr>
        </thead>

        <tbody>
          <% @user.following.each do |following| %>
          <tr>
               <td>
                <%= link_to following.username, relationship_user_path(@user.following, following) %>
               </td>
               
          </tr>
          <% end %>
        </tbody>
  </table>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render partial: 'shared/nav' %>


<div class="container w-content">
<%= form_for users_path, :method => 'get' do%>
  <%= text_field_tag :search, params[:search], placeholder:"Enter a name" %>
  <%= submit_tag "Search",class:"btn" %>
<%end%>
<div class="center-align">
<% @users.each do |user| %>
      <div class="collection">
            <%= link_to user_path(user), class:"collection-item", :action => 'go' do%>
              <div class="row valign-wrapper">
                <div class="col s12 m12 l6"><%= image_tag user_avatar(user, 75), class:"circle responsive-img", :title => "Visit #{user.username.capitalize} profile",alt: "user image" %></div>
                <div class="col s12 m12 l6"><%= user.username.capitalize %></div>
              </div>
            <%end%>
      </div>
    <%end%>
</div>
</div>

app/views/users/show.html.erb
<%= render partial: "shared/nav" %>
<div class="container w-container-user w-content">
    <div class="row">
        <div class="col s12 m12 l4">
            <div class="pic">
                <div class="img">
                    <%= image_tag user_avatar(@user, 300), class:"circle responsive-img", :title => @user.username.capitalize,alt: "user image" %>
                    
                </div>
                <div class="follow">
                </div>
            </div>
        </div>
        <div class="col s12 m12 l4">
             <div class="username">
                <h5>Username</h5>
                <%= @user.username.capitalize %>
            </div>
            <div class="bio">
                <h5>About</h5>
                <%= @user.about.capitalize %>
            </div>
            <div class="bio">
                <h5>Bio</h5>
                <%= @user.bio.capitalize %>
            </div>
            <div class="interest">
                <h5>Interests</h5>
                <%= @user.interest.field_of_interest %>
            </div>
        </div>
        <div class="col s12 m12 l4 follow">
             <% if current_user && current_user.following?(@user) %>
                        <%= render 'unfollow' %>
                        <% else %>
                        <%= render 'follow' %>
                    <% end %>
                    <%= render 'shared/relation' %><br>
            <%= link_to "Go to #{@user.username.capitalize} posts", users_posts_path(@user), class:"user-post" %>
        </div>
    </div>

</div>

app/views/users/user_posts.html.erb
<%= render partial: "shared/nav" %>

<div class="container w-content">
    <% if @posts.empty? %>
       <div class="not-found center-align">
            Empty!
        </div>
    <% else %>
      <div class="row">
      <% @posts.each do |post| %>
          
            <div class="col s12 m12 l4">
                <div class="post">
                    <%= link_to post_path(post), :action => 'go' do %>
                        <%= image_tag(post.image.variant(resize: "400x400").processed, :class => "user-img", alt: "user image") if post.image.attached?%><br>
                        <p><%= simple_format(post.content.truncate(100)) %></p><br>
                    <%end%>
                    <div class="row post-widgets">
                       Posted: <strong><%= post.created_at %><br></strong> 
                       Tag to: <strong><%= post.interest.field_of_interest %></strong> 
                    </div>
                </div>
            </div>
          
      <% end %>
      </div>
    <% end %>
</div>

     
 