config/routes.rb
Rails.application.routes.draw do

  get 'transition/show'
  devise_for :companies
  get 'public/index'
  get 'public/private'

  devise_for :users, controllers: { registrations: "registrations"} do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
    resources :posts
    resources :comments
    resources :interests
  end

  root to: "posts#index"

  resources :posts do
    member do
      put "like" => "posts#vote"
    end
    resources :users
    resources :interests
    post 'comments', to: 'comments#create'

  end

  resources :comments do
    resources :users
  end

  resources :users do
    resources :posts
    resources :interests
  end
  resources :interests do
    resources :posts
    resources :users
  end
  resources :relationships, only: [:create, :destroy] do
    resources :users
  end
  get 'users/:id/user_posts' => 'users#user_posts', :as => :users_posts
  get 'users/:id/current_user_posts' => 'users#current_user_posts', :as => :current_user_posts
  get 'interests/:id/post_by_interest' => 'interests#post_by_interest', :as => :posts_by_interest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_model.rb
class BusinessModel < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :text, presence: true


end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/interest.rb
class Interest < ApplicationRecord
    has_many :users
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :interest
  has_many :comments, dependent: :destroy
  has_one_attached :image

  scope :most_recent, -> { order(created_at: :desc) }

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"

    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_one_attached :avatar
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  belongs_to :interest
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships
 
  validates :email, :uniqueness => true
  validates :username, :uniqueness => true

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def self.search(search)
    if search
      where(["username LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?
    protected
    def configure_devise_parameters
        devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:username,:email,:password,:password_confirmation,:interest_id)}
        devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:avatar, :username,:email,:bio,:about, :interest_id ,:password,:current_password,:password_confirmation)}
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    include CommentsHelper
    before_action :authenticate_user!
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)
        @comment.user = current_user
        if @comment.save
            redirect_to post_path(@post)
            flash[:notice] = 'Comments added'
        else
            redirect_to post_path(@post)
            flash[:alert] = 'No comment added'
        end
  
    end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
    include InterestsHelper
    before_action :set_interest, only: [:show]
    before_action :authenticate_user!

    def index
        @interests = Interest.all
    end

    def post_by_interest
        @posts = current_user.interest.posts
    end

    def show
        @interest_post = @interest.posts
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    include PostsHelper
    include UsersHelper
    # before_action :set_user, only: %i[show]
    before_action :set_post, only: %i[show edit update edit destroy vote]
    before_action :authenticate_user!
    before_action :current_user, only: %i[index upvote new create]

    def index
        @posts = Post.all.most_recent
        @user_interest = current_user.interest
        @user_following = current_user.following
    end

    def show
        @comment = Comment.new
        @post_user = @post.user
        @comments = @post.comments.order(created_at: :desc)
    end

    def new
        @post = current_user.posts.build
    end

    def create
        @post = current_user.posts.build(post_params)

        if @post.save
            redirect_to posts_path
            flash[:notice] = 'Posted'
        else
            flash[:alert] = 'Failed'
            redirect_to posts_path
        end
    end

    def edit; end

    def update
        @post.update(post_params)
        redirect_to posts_path
    end

    def destroy
        Post.find(params[:id]).destroy
        redirect_to posts_path
    end

    def vote
      @post.upvote_by current_user
      redirect_back fallback_location: root_path
    end
    
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  include PostsHelper
  include UsersHelper
  # before_action :set_user, only: %i[index]


  def index; end

  def private; end
end

app/controllers/transition_controller.rb
class TransitionController < ApplicationController

  def show; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include UsersHelper
    before_action :set_user, only: %i[show user_posts]
    before_action :authenticate_user!
    def index
        @users = User.search(params[:search])
        # @users = User.all
    end

    def show; end

    def user_posts
        @posts = @user.posts
    end

    def current_user_posts
        @current_posts = current_user.posts
    end

    def edit
        @user_name = User.find(1)
    end
    
    def following
        @title = "Following"
        @user = User.find(params[:id])
        render 'following'
    end

    def followers
        @title = "Followers"
        @user = User.find(params[:id])
        render 'followers'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_avatar(user, size=40)
        if user.avatar.attached?
            user.avatar.variant(resize: "#{size}x#{size}")
        else
            gravatar_image_url(user.username, size: size)
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def comment_params
        params.require(:comment).permit(:text, :user_id, :post_id)
    end

    private

    def set_comment
        @comment = Comment.find(params[:id])
    end
end

app/helpers/interests_helper.rb
module InterestsHelper
    def interest_params
        params.require(:interest).permit(:field_of_interest, :post_id)
    end

    private

    def set_interest
        @interest = Interest.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_params
        params.require(:post).permit(:content, :user_id,:image,:interest_id,  :tag_list, :comment_id,:created_at)
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

    
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/transition_helper.rb
module TransitionHelper
 
end

app/helpers/users_helper.rb
module UsersHelper
    def user_params
        params.require(:user).permit(:email, :username, :avatar, :interest_id)
    end

    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
 <%= f.text_area :text, placeholder: "Post here" %>
 <%= f.submit %>
<% end %>

app/views/interests/index.html.erb
<%@interests.each do |i|%>
    <%= i.field_of_interest %>
<%end%>

app/views/interests/post_by_interest.html.erb
<%= render partial: "shared/nav" %>

<div class="container w-content">
    <% if @posts.empty? %>
       <div class="not-found center-align">
            Empty!
        </div>
    <% else %>
      <div class="row">
      <% @posts.each do |post| %>
          
            <div class="col s12 m12 l4">
                <div class="post">
                    <%= link_to post_path(post), :action => 'go' do %>
                        <%= image_tag(post.image.variant(resize: "400x400").processed, :class => "user-img", alt: "user image") if post.image.attached?%><br>
                        <p><%= simple_format(post.content.truncate(100)) %></p><br>
                    <%end%>
                    <div class="row post-widgets">
                       Posted: <strong><%= post.created_at %><br></strong> 
                        By: <strong><%= link_to post.user.username, post_user_path(post.user, post.user) %></strong> 
                    </div>
                </div>
            </div>
          
      <% end %>
      </div>
    <% end %>
</div>

     
 

app/views/interests/show.html.erb
<%= @interest.field_of_interest %>

<% @interest_post.each do |post_interest| %>
    <%= post_interest.content %>
<%end%>

app/views/posts/edit.html.erb
<%= render partial: 'shared/nav' %>

<div class="container w-content">
    <div class="row">
        <%= form_for @post do |f| %>
            <%= f.text_area :content, placeholder: "Post here" %>
            <%= f.submit "Edit a post", class:"btn" %>
        <% end %>
        <%= link_to  "Back to posts", posts_path %>
    </div>
</div>

app/views/posts/index.html.erb
<%= render partial: 'shared/nav' %>



        <div class="hide-on-large-only side-top center-align">
                <%= render 'shared/relation' %><br><br>
                <%= link_to  "New Post", new_post_path %><br><br><br>
        </div>
    
    <div class="container">
    <div class="row w-content">
        <div class="col s12 m12 l7 post-container box-a">
            <div class="interest-post center-align">
                <%= link_to "#{@user_interest.field_of_interest} posts", posts_by_interest_path(@user_interest) %>
            </div>
            <% @posts.each do |post| %>
                <div class="post">
                <%= link_to post_path(post), :action => 'go' do %>
                <%= image_tag(post.image, :class => "user-img responsive-img", alt: "user image") if post.image.attached?%><br>
                    <p><%= simple_format(post.content.truncate(200)) %></p><br>
                <%end%>

                    <div class="row post-widgets">
                        <div class="col s6 l6 m6">
                            Posted by: <strong><%= link_to post.user.username.capitalize, post_user_path(post, post.user)%></strong><br>
                            <%= link_to like_post_path(post), method: :put do%>
                                <span class="medium material-icons">thumb_up</span>
                                <%= post.get_upvotes.size %><br>
                        <% end %>
                        </div>
                        <div class="col s6 l6 m6 box-b">
                        <%= post.created_at %>
                        </div>
                    </div>
                    <div>
                    </div>Tag to: <%= post.interest.field_of_interest %></div>
                
            <%end%>
        </div>
        <div class="col s12 m12 l5 sidebar hide-on-med-and-down">
        <%= form_for Post.new, :url => posts_path(), :method => :post do |f| %>
         <%= f.text_area :content, placeholder: "Post here" %>
         <div class="fileUpload">
                    
        <span class="tooltip" title="Add a picture for your post"> <i class="small material-icons">add_a_photo</i></span>
            <%= f.file_field :image,direct_upload: true, accept:'application/jpeg,application/jpg,application/png,application/gif',class:"upload tooltip", title:"Add a picture for your post"%>
         </div>
         <%= f.label :field_of_interest, "Tag to" %>
         <%= f.collection_select(:interest_id, Interest.all, :id, :field_of_interest, :prompt => 'Tag to interest') %><br>
         <%= f.submit "Post",class:"btn post-btn" %>
        <% end %><br><br>
            <%= render 'shared/relation' %><br><br>

       
            
        </div>
    </div>
    </div>

app/views/posts/new.html.erb
<%= render partial:'shared/nav' %>
<div class="container w-content">
   <div class="row">
      <%= link_to  "Back to posts", posts_path %><br>
      <%= form_for @post do |f| %>
        <%= f.text_area :content, placeholder: "Post here" %>
         <div class="fileUpload">
                    
            <span class=""> <i class="small material-icons">add_a_photo</i></span>
            <%= f.file_field :image,direct_upload: true, accept:'application/jpeg,application/jpg,application/png,application/gif',class:"upload tooltip", title:"Add a picture for your post"%>
         </div>
         <%= f.label :field_of_interest, "Tag to" %>
         <%= f.collection_select(:interest_id, Interest.all, :id, :field_of_interest, :prompt => 'Tag to') %><br>
         <%= f.submit "Post",class:"btn post-btn" %>
      <% end %>
   </div>
</div>

app/views/posts/show.html.erb
<%= render partial: 'shared/nav' %>
    <div class="row posted">
        <div class="col s12 m12 l8">
        <div class="post">
            
            <p class="flow-text"><%= simple_format(@post.content) %></p>
            <%= link_to like_post_path(@post), method: :put do %>
            <span class="medium material-icons">thumb_up</span>
                <%= @post.get_upvotes.size %>
            <% end %>
            <div class="comment-title blue-text">
                <h6>Comments</h6>
            </div>
                <% @comments.each do |comment| %>
                    <div class="comments">
                        <p class="comment-paragraph"><%= comment.text %><br></p>
                        <strong>At</strong>: <%= comment.created_at.strftime("%H:%M-%Z") %><br>
                        <strong>By</strong>: <%= link_to comment.user.username.capitalize, comment_user_path(comment, comment.user) %>
                    </div>
                    <% end %>
        </div>
        </div>
        <div class="col s12 m12 l4 fixing">
            <div class="user-on-comments">
             From: <%= link_to @post_user.username.capitalize , post_user_path(@post, @post.user) %>
             <%= render 'shared/relation' %>
            </div>
            <div class="input-comments">
                <%= form_with model: [@post, @comment], local: true do |f| %>
                    <%= f.text_area :text,rows: 15 %>
                    <%= f.submit "Add a comment", class:"btn" %>
                <% end %>
                 <div class="back">
                    <%= link_to  "Back to posts", posts_path %>
                </div>
            </div>
        </div>
           
    </div>